<h2>第一題_算閏年：
<h3>請定義一個函式，讀進一個年份，輸出是不是閏年。

### 提示：
### 目前使用的格里高利曆閏年規則如下：

### 4的倍數是可能的。
### 100的倍數是不可能的。
### 400的倍數是可能的。

In [11]:
def lunar(x):
    if x%400 == 0:
        isLunar = True
    elif x%100 == 0:
        isLunar = False
    elif x%4 == 0:
        isLunar = True
    else:
        isLunar = False
    
    if isLunar:
        return str(x)+"年是閏年"
    else:
        return str(x)+"年不是閏年"

In [16]:
lunar(1985)

'1985年不是閏年'

In [17]:
lunar(1996)

'1996年是閏年'

In [18]:
lunar(2100)

'2100年不是閏年'

In [19]:
lunar(2400)

'2400年是閏年'

## 第二題_請實作五乘五矩陣的矩陣加法函式：

In [22]:
import numpy as np

In [29]:
def add(a, b):
    output = np.zeros((5, 5), dtype = int)
    for i in range(5):
        for j in range(5):
            output[i][j] = a[i][j] + b[i][j]
    return output

In [30]:
a = np.random.randint(1, 6, (5, 5))
b = np.random.randint(1, 6, (5, 5))

In [31]:
a

array([[1, 2, 5, 3, 1],
       [5, 3, 3, 2, 2],
       [2, 3, 5, 1, 1],
       [3, 1, 3, 2, 3],
       [1, 1, 2, 1, 5]])

In [32]:
b

array([[1, 1, 4, 4, 5],
       [2, 4, 2, 2, 3],
       [5, 1, 5, 3, 2],
       [3, 1, 3, 2, 3],
       [3, 4, 4, 5, 1]])

In [33]:
add(a, b)

array([[ 2,  3,  9,  7,  6],
       [ 7,  7,  5,  4,  5],
       [ 7,  4, 10,  4,  3],
       [ 6,  2,  6,  4,  6],
       [ 4,  5,  6,  6,  6]])

<h2>
第三題_錄取分數表格
<h4>
小明今年考大學
<h4>
依照 [“國文”, “英文”, “數甲”, “數乙”, “物理”, “化學”, “生物”, “歷史”, “地理”, “公民”]
<h4>
他的分數分別是 [86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6]
<h4>
而他所想申請的大學各系採計的科目權重分別是
 
<h4>{
<h4>“土語系”: [2, 2, 0, 1, 0, 0, 0, 1, 1, 0],
<h4>“財政系”: [1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],
<h4>“金融系”: [1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],
<h4>“國貿系”: [1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],
<h4>“會計系”: [1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],
<h4>“法律系”: [1, 2, 0, 1, 0, 0, 0, 1, 0, 1],
<h4>“公行系”: [1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],
<h4>“應數系”: [1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],
<h4>“教育系”: [1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]
<h4>}

<h4>請幫他做出一個表格
<h4>第一欄顯示科系
<h4>接下來顯示權重 並標示科目
<h4>最後一欄顯示加權分數

In [87]:
import pandas as pd

In [88]:
weights = np.array([
[2, 2, 0, 1, 0, 0, 0, 1, 1, 0],
[1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],
[1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],
[1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],
[1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],
[1, 2, 0, 1, 0, 0, 0, 1, 0, 1],
[1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],
[1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],
[1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]
])

In [89]:
majors = ['土語系', '財政系', '金融系', '國貿系', '會計系', '法律系', '公行系', '應數系', '教育系']
subjects = ["國文", "英文", "數甲", "數乙", "物理", "化學", "生物", "歷史", "地理", "公民"]
scores = [86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6]

In [90]:
data = pd.DataFrame(data = weights, index = majors, columns = subjects)
data["加權分數"] = (scores*weights).sum(axis = 1)

In [91]:
data

國文   英文   數甲    數乙   物理   化學   生物   歷史   地理    公民     加權分數
土語系  2.0  2.0  0.0  1.00  0.0  0.0  0.0  1.0  1.0  0.00  589.200
財政系  1.0  1.5  0.0  1.50  0.0  0.0  0.0  0.0  0.0  0.00  350.350
金融系  1.0  1.5  0.0  2.00  0.0  0.0  0.0  0.0  0.0  0.00  398.600
國貿系  1.5  2.0  0.0  2.00  0.0  0.0  0.0  0.0  0.0  0.00  481.550
會計系  1.5  2.0  0.0  2.00  0.0  0.0  0.0  1.0  1.0  0.00  642.450
法律系  1.0  2.0  0.0  1.00  0.0  0.0  0.0  1.0  0.0  1.00  508.900
公行系  1.0  1.5  0.0  1.25  0.0  0.0  0.0  0.0  0.0  1.25  436.975
應數系  1.0  1.0  1.5  0.00  1.0  1.0  0.0  0.0  0.0  0.00  461.300
教育系  1.5  2.0  0.0  1.25  0.0  0.0  0.0  1.0  1.0  0.00  570.075

## 挑戰題一_Bubble Sort
### Geoffrey是個喜歡自動化的老師，某次期中考過後，他想要把學生的成績用電腦自動排序，於是他請Andrew幫忙開發這個高難度的程式…

### 限制：不可以使用Python內建的sort()

### 提示：

### 每回合都把該回合範圍內最小的數搬到最左邊，最後就可以排好所有的數
### 搬運的方式可以透過兩兩互換

In [103]:
score = [60, 90, 50, 78, 82, 54, 30, 89, 70]

In [104]:
def sort(a):
    for i in range(len(a)):
        min_value = min(a[i:len(a)])
        a.remove(min_value)
        a.insert(i, min_value)
    return a

In [105]:
sort(score)

[30, 50, 54, 60, 70, 78, 82, 89, 90]