<h2> 第一題：
<h3>
有A,B,C三個班級，每班皆有10個學生，期中考結束後，老師希望計算各班級每位學生的加權平均成績。

<h3>
請隨機產生3個班級的成績單,每班10人,共五科,權重為weights=[0.25,0.25,0.25,0.15,0.10]。
<h3>
請算出班級加權平均成績，並以一個array輸出。

In [1]:
import numpy as np

In [ ]:
classes = np.random.randint(0, 101, size = (3, 10, 5))

In [ ]:
weights = np.array([0.25, 0.25, 0.25, 0.15, 0.1])

In [ ]:
classes

In [ ]:
classes * weights

In [ ]:
weighted_scores = classes * weights

In [ ]:
np.sum(weighted_scores, axis = 2)

In [ ]:
np.average(np.sum(weighted_scores, axis = 2), axis = 1)

## 第二題：
<h3>
向日葵班有40位學生，學期結束後，老師希望知道班上的期末成績相關資訊，作為下個學期教學的參考。


### 請隨機產生40筆0~100的數字作為向日葵班的成績分佈，
### 接著列出最高分、最低分、及格人數(>=60)、平均數、標準差，並且以10分作為一個區間，使用圖表畫出各個區間的人數。

In [ ]:
sunflower = np.random.randint(0, 100, 40)

In [ ]:
sunflower

In [ ]:
max(sunflower) #最高分

In [ ]:
min(sunflower) #最低分

In [ ]:
sunflower[sunflower >= 60].shape[0] #及格人數

In [ ]:
np.average(sunflower) #平均數

In [ ]:
np.std(sunflower) #標準差

In [2]:
import matplotlib.pyplot as plt

In [ ]:
plt.hist(sunflower, bins = [10*i for i in range(11)])
plt.show() #圖表

<h2>挑戰題一：

<h3>
請定義一個全班高微成績的函式，輸入是一個(3, 30, 3)的array，  
表示3個班級中30位學生的成績(小考，期中考，期末考)  。

目標輸出則是一個(3, 30, 1)的array，表示所有學生的期末成績，
期末成績計算方式如下：

1. 小考20%，期中考35%，期末考45%  
2. 期中考40%，期末考60%。  
擇優作為期末成績
 
Hint
* 可以用雙重for迴圈 分別跑過班級跟人
* 可以先設一個array裝算出來的成績
* 記得要用return 

In [11]:
def final(scores):
    weights1 = [0.2, 0.35, 0.45]
    weights2 = [0, 0.4, 0.6]
    
    final_score1 = np.sum(scores*weights1, axis = 2).ravel()
    final_score2 = np.sum(scores*weights2, axis = 2).ravel()
    final_score = np.zeros(90)
 
    for i in range(3*30):
        final_score[i] = max(final_score1[i], final_score2[i])
        
    final_score = final_score.reshape(3, 30, 1)

    return final_score
    


In [12]:
scores = np.random.randint(60, 101, (3, 30, 3))

In [13]:
final(scores)

array([[[77.6 ],
        [81.1 ],
        [91.8 ],
        [92.4 ],
        [83.6 ],
        [85.15],
        [79.2 ],
        [81.65],
        [70.35],
        [88.  ],
        [85.8 ],
        [73.15],
        [97.4 ],
        [92.6 ],
        [78.45],
        [84.4 ],
        [77.  ],
        [92.6 ],
        [93.4 ],
        [88.4 ],
        [91.2 ],
        [80.8 ],
        [70.4 ],
        [75.35],
        [86.4 ],
        [72.25],
        [88.6 ],
        [82.6 ],
        [76.7 ],
        [71.15]],

       [[85.75],
        [79.  ],
        [73.6 ],
        [72.2 ],
        [69.4 ],
        [79.7 ],
        [86.5 ],
        [70.2 ],
        [86.2 ],
        [83.35],
        [74.1 ],
        [79.95],
        [76.6 ],
        [75.  ],
        [80.2 ],
        [73.05],
        [78.9 ],
        [82.1 ],
        [93.2 ],
        [82.35],
        [73.3 ],
        [97.  ],
        [78.8 ],
        [82.  ],
        [79.5 ],
        [81.  ],
        [70.  ],
        [71.1 ],
        [71.

<h2> 挑戰題二：

<h3>
題目：給定一個矩陣m，裡面的值都大於0。
請將矩陣m裡大於等於1的數字都變成1，小於1的變成0。
<h3>
提示：使用巢狀迴圈(nested loop)加判斷式

In [20]:
m = np.random.rand(5, 5)*5

In [21]:
m

array([[3.28148701, 1.16618452, 1.4373259 , 1.98281932, 4.369456  ],
       [1.62967751, 2.52874859, 0.96619076, 4.45637832, 4.33172186],
       [1.19696661, 0.2435789 , 4.72453357, 0.51223414, 0.35045767],
       [1.68336234, 3.80228267, 2.511728  , 4.40098838, 0.23265251],
       [4.53853067, 1.93093883, 2.08501524, 1.24477249, 1.60321961]])

In [22]:
for i in range(m.shape[0]):
    for j in range(m.shape[1]):
        if m[i][j]>=1:
            m[i][j]=1
        else:
            m[i][j]=0

print(m)

[[1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 0. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]
